module.exports = {
    authenticateUser: require('./authenticate-user'),
    registerUser: require('./register-user'),
    retrieveUser: require('./retrieve-user'),
    retrievePublicUser: require('./retrieve-public-user'),
    modifyUser: require('./modify-user'),
    searchAds: require('./search-ads'),
    retrieveAd: require('./retrieve-ad'),
    retrieveAds: require('./retrieve-ads'),
    saveImageAd: require('./save-image-ad'),
    modifyAd: require('./modify-ad'),
    removeAd: require('./remove-ad'),
    saveImageProfile: require('./save-image-profile'),
    createAd: require('./create-ad'),
    retrievePublicAds: require('./retrieve-public-ads'),
    retrieveComments: require('./retrieve-comments'),
    addComment: require('./add-comment'),
    retrieveFavs: require('./retrieve-favs'),
    toggleFavAd: require('./toggle-fav-ad'),
    retrieveChats: require('./retrieve-chats'),
    retrieveChat: require('./retrieve-chat'),
    addMessage: require('./add-message'),
    removeChat: require('./remove-chat'),
    createChat: require('./create-chat')
}
