module.exports = {
    registerUser: require('./register-user'),
    authenticateUser: require('./authenticate-user'),
    retrieveUser: require('./retrieve-user'),
    retrieveBirthdays: require('./retrieve-bday-friend'),
    modifyUser: require('./modify-user'),
    saveProfileImage: require('./save-profile-image'),
    createWish: require('./create-wish'),
    saveWishImage: require('./save-wish-image'),
    modifyWish: require('./modify-wish'),
    removeWish: require('./delete-wish'),
    givenWish: require('./given-wish'),
    blockWish: require('./block-wish'),
    searchUsers: require('./search-users'),
    addFriend: require('./add-friend'),
    retrieveFriends: require('./retrieve-friends'),
    retrieveFriend: require('./retrieve-friend'),
    deleteFriend: require('./delete-friend'),
    saveFriendWish: require('./save-friend-wish'),
    retrieveFriendWish: require('./retrieve-saved-friend-wish'),
    removeFriendWish: require('./remove-friend-wish')
}