module.exports = {
    authenticateUser: require('./authenticate-user'),
    registerUser: require('./register-user'),
    retrieveUser: require('./retrieve-user'),
    modifyUser: require('./modify-user'),
    createAd: require('./create-ad'),
    removeAd: require('./remove-ad'),
    searchAds: require('./search-ads'),
    retrieveAds: require('./retrieve-ads'), 
    retrieveAd: require('./retrieve-ad'), 
    modifyAd: require('./modify-ad'), 
    createChat: require('./create-chat'),
    retrieveChat: require('./retrieve-chat'),
    retrieveChats: require('./retrieve-chats'),
    removeChat: require('./remove-chat'),
    addMessage: require('./add-message'),
    retrieveFavs: require('./retrieve-favs'),
    toggleFavAd: require('./toggle-fav-ad'),
    addComment: require('./add-comment'),
    retrieveComments: require('./retrieve-comments'),
    saveImageAd: require('./save-image-ad')
}
